---
- import_playbook: /infrastructure/ansible/setup.yml
- import_playbook: /infrastructure/ansible/monitoring.yml
  vars:
    datadog_api_key: DATADOG_API_KEY

- hosts: all
  remote_user: master
  become: yes
  vars:
    datadog_enabled: false
  tasks:
    - name: "Stop and disable datadog services"
      service:
        name: "{{ item }}"
        enabled: false
        state: stopped
      with_items:
        - datadog-agent
        - datadog-agent-trace
        - datadog-agent-process
